spring:
  application:
    name: ragtester

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  ai:
    ollama:
      base-url: ${OLLAMA_URL}
      embedding:
        options:
          model: ${EMBEDDING_MODEL}
      chat:
        options:
          model: ${CHAT_MODEL}
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
        max-document-batch-size: 10000
        schema-validation: true
        table-name: ${TABLE_NAME}


