spring:
  application:
    name: ragtester

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  ai:
    openai:
      base-url: ${OLLAMA_URL}
      api-key: ""
      embedding:
        options:
          model: ${EMBEDDING_MODEL}
          dimensions: ${EMBEDDING_DIM}
      chat:
        #base-url: ${OLLAMA_URL}
        api-key: ""
        options:
          model: ${CHAT_MODEL}
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: ${EMBEDDING_DIM}
        max-document-batch-size: 10000
        schema-validation: true
        table-name: ${TABLE_NAME}


